# Generated by Django 3.1.4 on 2020-12-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='IMG_20191128_200516_319.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee And Shakes', 'Coffee And Shakes'), ('Roll', 'Roll'), ('Starters', 'Fried Rice'), ('Fast Food', 'Fast Food'), ('Momos', 'Momos'), ('Noodles', 'Noodles'), ('Manchurian', 'Manchurian'), ('Sandwich', 'Sandwich'), ('Soup', 'Soup'), ('Fried Rice', 'Fried Rice'), ('Non-Veg Main Course', 'Non-Veg Main Course'), ('Biryani', 'Biryani'), ('Indian Sabji', 'Indian Sabji'), ('Roti / Paratha', 'Roti / Paratha'), ('EGG', 'EGG'), ('DAL', 'DAL'), ('Rice', 'Rice'), ('South Indian', 'South Indian'), ('THALI', 'THALI')], max_length=200, null=True),
        ),
    ]
