# Generated by Django 3.1.4 on 2020-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201217_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee And Shakes', 'Coffee And Shakes'), ('Roll', 'Roll'), ('Starters', 'Fried Rice'), ('Fast Food', 'Fast Food'), ('Momos', 'Momos'), ('Noodles', 'Noodles'), ('Manchurian', 'Manchurian'), ('Sandwich', 'Sandwich'), ('Soup', 'Soup'), ('Starters', 'Starters'), ('Non-Veg Main Course', 'Non-Veg Main Course'), ('Biryani', 'Biryani'), ('Indian Sabji', 'Indian Sabji'), ('Roti / Paratha', 'Roti / Paratha'), ('EGG', 'EGG'), ('DAL', 'DAL'), ('Rice', 'Rice'), ('South Indian', 'South Indian'), ('THALI', 'THALI')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
